[package]
name = "mobasserul_haque_individual_project2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.11", features = ["blocking"] }
rusqlite = { version = "^0.29", features = ["bundled"] }
csv = "^1.0"
