name: Rust CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: Update Linux
      run: sudo apt update 
    - name: Install Rust Toolchain
      run: make install
    - name: Check Rust Versions
      run: make rust-version
    - name: Format Code
      run: make format
    - name: Lint Code
      run: make lint
    - name: Run Tests
      run: make test
    - name: Run Insert Query
      run: make insert
    - name: Run Update Query
      run: make update
    - name: Run Read Query
      run: make read  
    - name: Run Delete Query
      run: make delete
    - name: Build Optimized Rust Binary
      run: make release
    - name: Upload Optimized Rust Binary
      uses: actions/upload-artifact@v3
      with:
        name: rust-binary
        path: target/release/mobasserul_haque_individual_project2
